
import type { Page } from './types';
import { ChartType } from './types';
import { SalesIcon, InventoryIcon, CustomerServiceIcon, FinanceIcon } from './components/icons/Icons';

export const PAGES: Page[] = [
  {
    name: "Sales & Marketing",
    description: "View sales performance, campaigns, payments, and customer spending.",
    icon: SalesIcon,
    queries: [
      {
        title: "Top Selling Products",
        sql: `
          SELECT product_name,
                 SUM(quantity)      AS total_units_sold,
                 SUM(total_amount)  AS total_revenue
          FROM sales_data
          GROUP BY product_name
          ORDER BY total_revenue DESC;
        `,
        chartType: ChartType.BAR,
        description: "Revenue per product",
      },
      {
        title: "Daily Revenue Trends",
        sql: `
          SELECT order_date,
                 SUM(total_amount) AS daily_revenue,
                 COUNT(order_id)   AS orders_count
          FROM sales_data
          GROUP BY order_date
          ORDER BY order_date;
        `,
        chartType: ChartType.LINE,
        description: "Revenue over the last 30 days",
      },
      {
        title: "Payments by Method",
        sql: `
          SELECT payment_method,
                 COUNT(*)            AS transactions,
                 SUM(total_amount)   AS revenue
          FROM sales_data
          GROUP BY payment_method;
        `,
        chartType: ChartType.PIE,
        description: "Distribution of payment methods",
      },
      {
        title: "Top 10 Customers by Spending",
        sql: `
          SELECT customer_name,
                 SUM(total_amount) AS total_spent,
                 COUNT(order_id)   AS orders_made
          FROM sales_data
          GROUP BY customer_name
          ORDER BY total_spent DESC
          LIMIT 10;
        `,
        chartType: ChartType.TABLE,
        description: "Most valuable customers",
      },
      {
        title: "Campaign Performance",
        sql: `
          SELECT campaign_name,
                 SUM(revenue_generated) AS campaign_revenue,
                 SUM(clicks)            AS total_clicks
          FROM sales_data
          GROUP BY campaign_name
          ORDER BY campaign_revenue DESC;
        `,
        chartType: ChartType.BAR,
        description: "Revenue generated by marketing campaigns",
      },
      {
        title: "Revenue by Platform",
        sql: `
          SELECT platform,
                 ROUND(AVG(total_amount), 2) AS avg_order_value,
                 SUM(total_amount)           AS total_revenue
          FROM sales_data
          GROUP BY platform
          ORDER BY total_revenue DESC;
        `,
        chartType: ChartType.BAR,
        description: "Sales performance across platforms",
      },
      {
        title: "Orders by Payment Status",
        sql: `
          SELECT payment_status,
                 COUNT(*)          AS orders,
                 SUM(total_amount) AS total_value
          FROM sales_data
          GROUP BY payment_status;
        `,
        chartType: ChartType.PIE,
        description: "Status of order payments",
      },
    ]
  },
  {
    name: "Inventory & Supply Chain",
    description: "Track stock movements, supplier orders, and product availability.",
    icon: InventoryIcon,
    queries: [
      {
        title: "Sample Inventory Levels",
        sql: `
          SELECT 'Manila Warehouse' as location, 'Electronics' as category, 540 as stock_count
          UNION ALL
          SELECT 'Cebu Distribution', 'Home & Kitchen', 320
          UNION ALL
          SELECT 'Davao Service Center', 'Fashion & Clothing', 120;
        `,
        chartType: ChartType.TABLE,
        description: "Stock levels across locations",
      },
    ]
  },
  {
    name: "Customer Service",
    description: "Analyze support tickets, returns, and customer feedback.",
    icon: CustomerServiceIcon,
    queries: [
      {
        title: "Sample Ticket Resolution",
        sql: `
          SELECT 'Quezon City' as branch, 85 as tickets_open, 420 as tickets_resolved
          UNION ALL
          SELECT 'Iloilo Hub', 60, 390;
        `,
        chartType: ChartType.TABLE,
        description: "Support ticket status by branch",
      },
    ]
  },
  {
    name: "Finance",
    description: "View revenue, expenses, and profit margins.",
    icon: FinanceIcon,
    queries: [
      {
        title: "Mock Profit Margins by Department",
        sql: `
          SELECT 'Sales & Marketing' as department, 1250000 as revenue, 870000 as expenses, 380000 as profit
          UNION ALL
          SELECT 'Inventory', 980000, 700000, 280000
          UNION ALL
          SELECT 'Customer Service', 320000, 210000, 110000;
        `,
        chartType: ChartType.TABLE,
        description: "Financial overview by department",
      },
    ]
  }
];
